source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'FBSDKCoreKit', '~> 9.3'
  pod 'FBSDKGamingServicesKit', '~> 9.3'
  pod 'FBSDKLoginKit', '~> 9.3'
  pod 'FBSDKShareKit', '~> 9.3'
end
target 'Unity-iPhone' do
end
use_frameworks!
